services:
  - type: web
    name: youtube-bulk-downloader
    env: node
    buildCommand: |
      npm install
      npm run build
      # Install yt-dlp
      curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /opt/render/project/src/yt-dlp
      chmod +x /opt/render/project/src/yt-dlp
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 