services:
  - type: web
    name: youtube-bulk-downloader
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: downloads
      mountPath: /opt/render/project/src/downloads
      sizeGB: 10 